"""email feature added

Revision ID: 435e229340ba
Revises: de9bf00eb89c
Create Date: 2024-01-31 10:43:18.716129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435e229340ba'
down_revision = 'de9bf00eb89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safetyplans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safetyplans', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
